In [1]:
import numpy as np
np.array(['Keith',2,3])

array(['Keith', '2', '3'], dtype='<U11')

In [2]:
np.array([1,2,3,4,'vbvg'])

array(['1', '2', '3', '4', 'vbvg'], dtype='<U11')

In [3]:
np.array([1,2,3.])

array([1., 2., 3.])

In [4]:
np.array([[1,3],[2,3]])

array([[1, 3],
       [2, 3]])

In [5]:
b=np.array([1,2,3],ndmin=5)

In [6]:
b

array([[[[[1, 2, 3]]]]])

In [7]:
np.array([1,2,3,4],dtype='U11')

array(['1', '2', '3', '4'], dtype='<U11')

In [8]:
x=np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])

In [9]:
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [10]:
x[0][1]

2

In [11]:
type(x[0][1])

numpy.int64

In [12]:
x[0][0]

1

In [13]:
type(x[0][0])

numpy.int16

In [14]:
np.array([[1,2],[2,4]])

array([[1, 2],
       [2, 4]])

In [15]:
np.mat(np.array([[1,2],[2,4]]))

matrix([[1, 2],
        [2, 4]])

In [16]:
k=[1,2]

In [17]:
np.asarray(k)

array([1, 2])

In [18]:
np.array(k)

array([1, 2])

In [19]:
m=np.matrix([1,2])
m

matrix([[1, 2]])

In [20]:
np.array(m)

array([[1, 2]])

In [21]:
np.asarray(m)

array([[1, 2]])

In [22]:
np.asanyarray(m)

matrix([[1, 2]])

In [23]:
y=np.array([1,2,3])
y

array([1, 2, 3])

In [24]:
x=y

In [25]:
y

array([1, 2, 3])

In [26]:
y[0]=5

In [27]:
y

array([5, 2, 3])

In [28]:
x

array([5, 2, 3])

In [29]:
d=np.copy(x)

In [30]:
d[0]

5

In [31]:
d[0]=2

In [32]:
d

array([2, 2, 3])

In [33]:
x

array([5, 2, 3])

# numpy fromfunction

In [34]:
x

array([5, 2, 3])

In [35]:
np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [36]:
np.fromfunction(lambda i,j:i*j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [37]:
np.fromfunction(lambda i,j,k,m:i*j*k*m,(3,3,3,3),dtype=int)

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]]]])

In [38]:
np.fromstring('234 234',sep=" ")

array([234., 234.])

In [39]:
np.fromstring('1 , 2',dtype=int,sep=',')

array([1, 2])

In [40]:
my_list=[1,2,4]
arr=np.array(my_list)
print('type of the array',type(arr))
print('vector\n-----------\n',arr)

type of the array <class 'numpy.ndarray'>
vector
-----------
 [1 2 4]


In [41]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.matrix(my_mat)
print('Type',type(mat))
print('Here is the matrix\n--------\n',mat,'\n--------\n')
print('Here is the dimension',mat.ndim,sep='')
print('Here is the size',mat.size,sep='')
print('Here is the shape',mat.shape,sep='')
print('Data Type',mat.dtype,sep='')


Type <class 'numpy.matrix'>
Here is the matrix
--------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
--------

Here is the dimension2
Here is the size9
Here is the shape(3, 3)
Data Typeint32


# arange and linspace

In [46]:
a=range(4,7)

In [51]:
b=iter(a)


In [53]:
next(b)

5

In [56]:
np.arange(2.2,50.4,2)

array([ 2.2,  4.2,  6.2,  8.2, 10.2, 12.2, 14.2, 16.2, 18.2, 20.2, 22.2,
       24.2, 26.2, 28.2, 30.2, 32.2, 34.2, 36.2, 38.2, 40.2, 42.2, 44.2,
       46.2, 48.2, 50.2])

In [57]:
np.linspace(1,5,50)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

TypeError: Cannot interpret '10' as a data type

# Matrix Creation

In [62]:
print('Vector of zeros\n-----------')
print(np.zeros(5))

Vector of zeros
-----------
[0. 0. 0. 0. 0.]


In [63]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
np.zeros((4,4,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
 

In [72]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [77]:
np.zeros((3,4,8))+5*2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [78]:
np.linspace(4,8,80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [79]:
np.ones((3,3,3))+5

array([[[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

In [85]:
np.arange(16,).reshape((16,-1 ))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [81]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
np.arange(16).reshape(8,2,1)

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]],

       [[12],
        [13]],

       [[14],
        [15]]])

In [90]:
np.arange(16).reshape((-1.44,8))

TypeError: 'float' object cannot be interpreted as an integer

In [93]:
c=np.arange(16).reshape(-1,4)

In [94]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [95]:
np.diag(c)

array([ 0,  5, 10, 15])

In [106]:
np.diag(c,k=2)

array([2, 7])

In [108]:
np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [109]:
np.diagflat([[1,2],[3,4]],k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [115]:
k=np.matrix([[1,2,3,4],[7,8,9,10]])
k.shape

(2, 4)

In [116]:
f=np.matrix([[11,22,33,44],[13,12,33,46]])
f.shape

(2, 4)

In [117]:
k+5

matrix([[ 6,  7,  8,  9],
        [12, 13, 14, 15]])

In [120]:
k+f

matrix([[12, 24, 36, 48],
        [20, 20, 42, 56]])

In [127]:
np.tril([[1,2,3],[4,5,6]],1)

array([[1, 2, 0],
       [4, 5, 6]])

In [128]:
np.triu([[1,2,3],[4,5,6]],1)

array([[0, 2, 3],
       [0, 0, 6]])

In [129]:
np.random.rand(2,3,8)

array([[[0.49370169, 0.13707681, 0.88815751, 0.42386211, 0.63021069,
         0.64975412, 0.26688979, 0.26500381],
        [0.60238564, 0.9190672 , 0.15995988, 0.94387646, 0.32485205,
         0.08693711, 0.87815417, 0.98396954],
        [0.9837889 , 0.67258698, 0.32525699, 0.26312129, 0.57002707,
         0.24120033, 0.3745278 , 0.75548887]],

       [[0.64852386, 0.57223016, 0.25062621, 0.08392717, 0.11101616,
         0.13906716, 0.44720736, 0.50407407],
        [0.06552149, 0.72795191, 0.50011171, 0.9761203 , 0.53466187,
         0.95359172, 0.80500512, 0.64705823],
        [0.15638053, 0.84298787, 0.18454516, 0.55721414, 0.50665386,
         0.57947815, 0.56475536, 0.12722472]]])

In [130]:
np.random.randn(4,5)

array([[ 0.64481021, -0.30532166, -1.27515318,  0.30669113, -0.59282681],
       [-0.37844251, -0.2194915 ,  1.19045814,  0.08195112,  0.60678621],
       [ 1.39378942,  0.03903888,  0.53019629,  0.03600112, -0.54935356],
       [ 0.18822114,  0.6090477 , -1.48927537, -0.01454989, -1.05735619]])

In [133]:
np.random.randint(1,3)

2

In [134]:
np.random.randint(1,100,(4,4))

array([[31, 63, 16,  9],
       [59, 16,  7, 81],
       [62, 22, 59, 48],
       [35, 92, 90, 87]])

In [140]:
a=np.random.randint(1,100,30)
a

array([76, 96, 86, 17,  9,  6, 49, 96, 20, 85, 10, 65,  3, 38, 31, 71, 65,
       87, 72,  2, 10, 97, 91, 32, 90, 40, 88, 17, 70, 47])

In [137]:
b=a.reshape(2,3,5)

In [138]:
b

array([[[47, 96, 14, 13, 79],
        [35,  8,  4, 83, 43],
        [91, 68, 98, 49,  9]],

       [[87, 52, 59, 12, 74],
        [46, 56,  3, 62, 34],
        [39, 82, 96, 77, 15]]])

In [139]:
a

array([47, 96, 14, 13, 79, 35,  8,  4, 83, 43, 91, 68, 98, 49,  9, 87, 52,
       59, 12, 74, 46, 56,  3, 62, 34, 39, 82, 96, 77, 15])

In [159]:
c=a.reshape(6,-1333)

In [160]:
c

array([[76, 96, 86, 17,  9],
       [ 6, 49, 96, 20, 85],
       [10, 65,  3, 38, 31],
       [71, 65, 87, 72,  2],
       [10, 97, 91, 32, 90],
       [40, 88, 17, 70, 47]])

In [161]:
np.sort(c)

array([[ 9, 17, 76, 86, 96],
       [ 6, 20, 49, 85, 96],
       [ 3, 10, 31, 38, 65],
       [ 2, 65, 71, 72, 87],
       [10, 32, 90, 91, 97],
       [17, 40, 47, 70, 88]])

In [164]:
g=np.sort(c,axis=1)

In [166]:
g

array([[ 9, 17, 76, 86, 96],
       [ 6, 20, 49, 85, 96],
       [ 3, 10, 31, 38, 65],
       [ 2, 65, 71, 72, 87],
       [10, 32, 90, 91, 97],
       [17, 40, 47, 70, 88]])

In [165]:
g.max()

97

In [167]:
np.argmax(g)

24

# Indexing and Slcicing

In [170]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [172]:
np.argmax(arr)

10

In [173]:
mat1=np.random.randint(10,100,15).reshape(3,5)

In [174]:
mat1

array([[53, 18, 61, 68, 98],
       [46, 93, 21, 60, 79],
       [46, 86, 63, 26, 14]])

In [175]:
mat1[1:4,3:5]

array([[60, 79],
       [26, 14]])

In [179]:
mat1[2,[4]]

array([14])

In [184]:
mat2=np.array(np.random.randint(10,100,45)).reshape(3,5,3)

In [185]:
mat2

array([[[14, 22, 98],
        [56, 86, 42],
        [42, 41, 29],
        [39, 79, 80],
        [90, 42, 52]],

       [[81, 47, 91],
        [16, 60, 70],
        [47, 56, 51],
        [30, 41, 31],
        [19, 18, 33]],

       [[27, 47, 59],
        [26, 70, 84],
        [66, 85, 81],
        [83, 51, 64],
        [78, 83, 43]]])

In [194]:
mat2[0][2,1]

41

In [217]:
mat2[0:3,[0,1]]

array([[[14, 22, 98],
        [56, 86, 42]],

       [[81, 47, 91],
        [16, 60, 70]],

       [[27, 47, 59],
        [26, 70, 84]]])

In [220]:
for i in range(len(mat2)):
    print(mat2[i][:2,:])

[[14 22 98]
 [56 86 42]]
[[81 47 91]
 [16 60 70]]
[[27 47 59]
 [26 70 84]]


In [222]:
slice=np.array([[11,12,13],[21,22,23],[31,32,33]])
slice

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [225]:
mat_slice=slice[:2,:2]

In [226]:
mat_slice

array([[11, 12],
       [21, 22]])

array([1, 2, 3, 4])

In [228]:
np.sqrt(mat2)

array([[[3.74165739, 4.69041576, 9.89949494],
        [7.48331477, 9.2736185 , 6.4807407 ],
        [6.4807407 , 6.40312424, 5.38516481],
        [6.244998  , 8.88819442, 8.94427191],
        [9.48683298, 6.4807407 , 7.21110255]],

       [[9.        , 6.8556546 , 9.53939201],
        [4.        , 7.74596669, 8.36660027],
        [6.8556546 , 7.48331477, 7.14142843],
        [5.47722558, 6.40312424, 5.56776436],
        [4.35889894, 4.24264069, 5.74456265]],

       [[5.19615242, 6.8556546 , 7.68114575],
        [5.09901951, 8.36660027, 9.16515139],
        [8.1240384 , 9.21954446, 9.        ],
        [9.11043358, 7.14142843, 8.        ],
        [8.83176087, 9.11043358, 6.55743852]]])

In [230]:
np.exp(mat2)

array([[[1.20260428e+06, 3.58491285e+09, 3.63797095e+42],
        [2.09165950e+24, 2.23524660e+37, 1.73927494e+18],
        [1.73927494e+18, 6.39843494e+17, 3.93133430e+12],
        [8.65934004e+16, 2.03828107e+34, 5.54062238e+34],
        [1.22040329e+39, 1.73927494e+18, 3.83100800e+22]],

       [[1.50609731e+35, 2.58131289e+20, 3.31740010e+39],
        [8.88611052e+06, 1.14200739e+26, 2.51543867e+30],
        [2.58131289e+20, 2.09165950e+24, 1.40934908e+22],
        [1.06864746e+13, 6.39843494e+17, 2.90488497e+13],
        [1.78482301e+08, 6.56599691e+07, 2.14643580e+14]],

       [[5.32048241e+11, 2.58131289e+20, 4.20121040e+25],
        [1.95729609e+11, 2.51543867e+30, 3.02507732e+36],
        [4.60718663e+28, 8.22301271e+36, 1.50609731e+35],
        [1.11286375e+36, 1.40934908e+22, 6.23514908e+27],
        [7.49841700e+33, 1.11286375e+36, 4.72783947e+18]]])

ValueError: operands could not be broadcast together with shapes (3,5,3) (3,5) 