In [1]:
import numpy as np
np.array(['Keith',2,3])

array(['Keith', '2', '3'], dtype='<U11')

In [2]:
np.array([1,2,3,4,'vbvg'])

array(['1', '2', '3', '4', 'vbvg'], dtype='<U11')

In [3]:
np.array([1,2,3.])

array([1., 2., 3.])

In [4]:
np.array([[1,3],[2,3]])

array([[1, 3],
       [2, 3]])

In [5]:
b=np.array([1,2,3],ndmin=5)

In [6]:
b

array([[[[[1, 2, 3]]]]])

In [7]:
np.array([1,2,3,4],dtype='U11')

array(['1', '2', '3', '4'], dtype='<U11')

In [8]:
x=np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])

In [9]:
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [10]:
x[0][1]

2

In [11]:
type(x[0][1])

numpy.int64

In [12]:
x[0][0]

1

In [13]:
type(x[0][0])

numpy.int16

In [14]:
np.array([[1,2],[2,4]])

array([[1, 2],
       [2, 4]])

In [15]:
np.mat(np.array([[1,2],[2,4]]))

matrix([[1, 2],
        [2, 4]])

In [16]:
k=[1,2]

In [17]:
np.asarray(k)

array([1, 2])

In [18]:
np.array(k)

array([1, 2])

In [19]:
m=np.matrix([1,2])
m

matrix([[1, 2]])

In [20]:
np.array(m)

array([[1, 2]])

In [21]:
np.asarray(m)

array([[1, 2]])

In [22]:
np.asanyarray(m)

matrix([[1, 2]])

In [23]:
y=np.array([1,2,3])
y

array([1, 2, 3])

In [24]:
x=y

In [25]:
y

array([1, 2, 3])

In [26]:
y[0]=5

In [27]:
y

array([5, 2, 3])

In [28]:
x

array([5, 2, 3])

In [29]:
d=np.copy(x)

In [30]:
d[0]

5

In [31]:
d[0]=2

In [32]:
d

array([2, 2, 3])

In [33]:
x

array([5, 2, 3])

# numpy fromfunction

In [34]:
x

array([5, 2, 3])

In [35]:
np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [36]:
np.fromfunction(lambda i,j:i*j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [37]:
np.fromfunction(lambda i,j,k,m:i*j*k*m,(3,3,3,3),dtype=int)

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]]]])

In [38]:
np.fromstring('234 234',sep=" ")

array([234., 234.])

In [39]:
np.fromstring('1 , 2',dtype=int,sep=',')

array([1, 2])

In [40]:
my_list=[1,2,4]
arr=np.array(my_list)
print('type of the array',type(arr))
print('vector\n-----------\n',arr)

type of the array <class 'numpy.ndarray'>
vector
-----------
 [1 2 4]


In [41]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.matrix(my_mat)
print('Type',type(mat))
print('Here is the matrix\n--------\n',mat,'\n--------\n')
print('Here is the dimension',mat.ndim,sep='')
print('Here is the size',mat.size,sep='')
print('Here is the shape',mat.shape,sep='')
print('Data Type',mat.dtype,sep='')


Type <class 'numpy.matrix'>
Here is the matrix
--------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
--------

Here is the dimension2
Here is the size9
Here is the shape(3, 3)
Data Typeint32


# arange and linspace

In [46]:
a=range(4,7)

In [51]:
b=iter(a)


In [53]:
next(b)

5

In [56]:
np.arange(2.2,50.4,2)

array([ 2.2,  4.2,  6.2,  8.2, 10.2, 12.2, 14.2, 16.2, 18.2, 20.2, 22.2,
       24.2, 26.2, 28.2, 30.2, 32.2, 34.2, 36.2, 38.2, 40.2, 42.2, 44.2,
       46.2, 48.2, 50.2])

In [57]:
np.linspace(1,5,50)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

TypeError: Cannot interpret '10' as a data type

# Matrix Creation

In [62]:
print('Vector of zeros\n-----------')
print(np.zeros(5))

Vector of zeros
-----------
[0. 0. 0. 0. 0.]


In [63]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
np.zeros((4,4,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
 

In [72]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [77]:
np.zeros((3,4,8))+5*2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [78]:
np.linspace(4,8,80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [79]:
np.ones((3,3,3))+5

array([[[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])